name: Lint

on: [pull_request]

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  cpp-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Run cpp-linter (Report)
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'  # Use .clang-format
          tidy-checks: '-*,bugprone-*,clang-analyzer-*,google-*,modernize-*,performance-*,portability-*,readability-*,-modernize-use-trailing-return-type,-readability-identifier-length,-readability-uppercase-literal-suffix'
          files-changed-only: false
          thread-comments: true
          step-summary: true
          database: '' 
          extra-args: >-
            -std=c++17
            -I./source
            -I./engine/source
            -I./engine/thirdparty/glfw-3.4/include
            -I./engine/thirdparty/glew/include
          ignore: 'engine/thirdparty|build|cmake-build-*'

      - name: Fail if linter found errors
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Linter found errors" && exit 1
